spring:
  datasource: { url: jdbc:postgresql://localhost:9999/ecommerce, username: kimthoy, password: kimthoy, driver-class-name: org.postgresql.Driver }
liquibase:
  enabled: true
  change-log: classpath:db/changelog/db.changelog-master.yaml
  liquibaseSchemaName: public
outputChangeLogFile: src/main/resources/liquibase-outputChangeLog.yml